#!/bin/sh

lb config noauto \
	-d sid \
	--apt-recommends false \
	--archive-areas "main non-free contrib" \
	--apt-indices false \
	--hdd-label LIVE-MINER \
	--iso-application live-miner \
	--iso-publisher 'live-miner; http://live-miner.github.com/' \
	--iso-volume "live-miner $(date +%Y%m%d-%H:%M)" \
	--compression none \
	"${@}"
